#ifndef COORDINADOR_CONNECTION_ESI_CONNECTION_H_
#define COORDINADOR_CONNECTION_ESI_CONNECTION_H_

#define CHECK_RECV_WITH_SIZE(FD, BLOCK, BLOCK_SIZE) (recv(FD, BLOCK, BLOCK_SIZE, MSG_WAITALL) != (BLOCK_SIZE))
#define CHECK_RECV(FD, BLOCK) CHECK_RECV_WITH_SIZE(FD, BLOCK, sizeof(*(BLOCK)))

void handle_esi_connection(int fd);

#endif /* COORDINADOR_CONNECTION_ESI_CONNECTION_H_ */
