#ifndef COORDINADOR_CONNECTION_INSTANCE_CONNECTION_H_
#define COORDINADOR_CONNECTION_INSTANCE_CONNECTION_H_

void handle_instance_connection(int fd);

#endif /* COORDINADOR_CONNECTION_INSTANCE_CONNECTION_H_ */
