#ifndef PROTOCOL_PROTOCOL_H_
#define PROTOCOL_PROTOCOL_H_

typedef enum {
	PROTOCOL_ANY_CLOSE_CONNECTION,
	PROTOCOL_ANY_HANDSHAKE,
	PROTOCOL_ANY_SEND_MSG,
	PROTOCOL_PE_EXEC,
	PROTOCOL_EC_SET,
	PROTOCOL_CI_PERSIST_KEY,
	PROTOCOL_IC_PERSIST_KEY_SUCCESS,
	PROTOCOL_CP_PERSIST_SUCCESS,
	PROTOCOL_EC_GET,
	PROTOCOL_CP_BLOCK_KEY
} protocol_id;

#endif
