#ifndef PROTOCOLO_PROTOCOLO_COORDINADOR_INSTANCIA_H_
#define PROTOCOLO_PROTOCOLO_COORDINADOR_INSTANCIA_H_

typedef enum {
	PROTOCOL_CI_HANDSHAKE_CONFIRMATION,
	PROTOCOL_CI_SET,
	PROTOCOL_CI_STORE,
	PROTOCOL_CI_COMPACT,
	PROTOCOL_CI_REQUEST_VALUE,
	PROTOCOL_CI_KILL
} request_coordinador;

typedef enum {
	PROTOCOL_IC_HANDSHAKE,
	PROTOCOL_IC_NOTIFY_STATUS,
	PROTOCOL_IC_NOTIFY_STORE,
	PROTOCOL_IC_RETRIEVE_VALUE,
	PROTOCOL_IC_DIE
} request_instancia;

typedef enum {
	STATUS_COMPACT = 2,
	STATUS_OK = 1,
	STATUS_REPLACED = 0,
	STATUS_NO_SPACE = -1
} status_ci;

#endif
