#ifndef PROTOCOLO_PROTOCOLO_COORDINADOR_INSTANCIA_H_
#define PROTOCOLO_PROTOCOLO_COORDINADOR_INSTANCIA_H_

typedef enum {
	PROTOCOL_CI_HANDSHAKE_CONFIRMATION,
	PROTOCOL_CI_SET,
	PROTOCOL_CI_STORE,
	PROTOCOL_CI_KILL,
	PROTOCOL_CI_COMPACTATION
} request_coordinador;

typedef enum {
	PROTOCOL_IC_HANDSHAKE,
	PROTOCOL_IC_NOTIFY_STATUS,
	PROTOCOL_IC_NOTIFY_STORE,
	PROTOCOL_IC_DIE,
	PROTOCOL_IC_NOTIFY_COMPACTATION
} request_instancia;

#endif
